### ISSUE TITLE
Unexpected error while adding SUN2000

### ISSUE THREAD

**Issue by dMopp** [wlcrs/huawei_solar#116]
Hi, i tried to add my brand new SUN2000-5KTL-M1 and got the following error in the log:

```
Aug 23 14:59:45 ulli be7606b67c2f[680]: #033[31m2022-08-23 14:59:45.687 ERROR (MainThread) [custom_components.huawei_solar.config_flow] 'PrivateHuaweiModbusResponse' object has no attribute 'registers'
Aug 23 14:59:45 ulli be7606b67c2f[680]: Traceback (most recent call last):
Aug 23 14:59:45 ulli be7606b67c2f[680]:   File "/config/custom_components/huawei_solar/config_flow.py", line 225, in async_step_setup_serial
Aug 23 14:59:45 ulli be7606b67c2f[680]:     info = await validate_serial_setup(user_input)
Aug 23 14:59:45 ulli be7606b67c2f[680]:   File "/config/custom_components/huawei_solar/config_flow.py", line 53, in validate_serial_setup
Aug 23 14:59:45 ulli be7606b67c2f[680]:     bridge = await HuaweiSolarBridge.create_rtu(
Aug 23 14:59:45 ulli be7606b67c2f[680]:   File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 94, in create_rtu
Aug 23 14:59:45 ulli be7606b67c2f[680]:     await HuaweiSolarBridge.__populate_fields(bridge)
Aug 23 14:59:45 ulli be7606b67c2f[680]:   File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 118, in __populate_fields
Aug 23 14:59:45 ulli be7606b67c2f[680]:     model_name_result, serial_number_result = await bridge.client.get_multiple(
Aug 23 14:59:45 ulli be7606b67c2f[680]:   File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 292, in get_multiple
Aug 23 14:59:45 ulli be7606b67c2f[680]:     response.registers, byteorder=Endian.Big, wordorder=Endian.Big
Aug 23 14:59:45 ulli be7606b67c2f[680]: AttributeError: 'PrivateHuaweiModbusResponse' object has no attribute 'registers'#033[0m
Aug 23 15:00:01 ulli systemd[1]: Started Checkmk agent (192.168.20.1:52384).
```

Did i something wrong? The Device is connected over the 2 Cables to the USB-Stick but thats the result  :( (As described in the Wiki) and the Settings in the Device Itself are as described, too

**Comment by wlcrs** [comment]
Please fill out the bug report issue template instead of using a blank issue. Make sure to include the extended logs including those of pymodbus

**Comment by dMopp** [comment]
Hi, how i find the extended logs? verything else is prepared. and sorry for that !
