### ISSUE TITLE
[Bug]: bad operand type for abs(): 'NoneType'

### ISSUE THREAD

**Issue by kristianolofsson** [wlcrs/huawei_solar#137]
### System Health details

After installing a smartmeter and battery i reloaded the integrastion but get error. I then tried to remove it and reinstall but get the same.

### Huawei Solar Setup

I use a network connection and apply the IP, port 502, powermeter is 3-phase and a battery Luna 15kwh.
I got all the data before i tried to reload.

### Describe the issue

The error shows only after i did a reload of integration, i was just affraid i missed anything. 

### Relevant debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/huawei_solar/__init__.py", line 250, in _async_update_data
    return await self.bridge.update()
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 192, in update
    result.update(await _get_multiple_to_dict(POWER_METER_REGISTERS))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 179, in _get_multiple_to_dict
    zip(names, await self.client.get_multiple(names, self.slave_id))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 303, in get_multiple
    result.append(await self._decode_response(registers[idx], decoder))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 237, in _decode_response
    result = reg.decode(decoder, self)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/registers.py", line 200, in decode
    return abs(super().decode(decoder, inverter))
TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by wlcrs** [comment]
What is the exact type of smart meter have you installed? Is it working
correctly in FusionSolar?
