### ISSUE TITLE
[Bug]: Another blackout after update from 8.5 to 9.0 core HASS

### ISSUE THREAD

**Issue by razvanu** [wlcrs/huawei_solar#138]
### System Health details

![image](https://user-images.githubusercontent.com/15201014/190388005-73d9824e-9ef5-4a9b-a354-b97c99b18957.png)

### Huawei Solar Setup

Sun2000 3KTL with S-Dongle, + battery

### Describe the issue

![image](https://user-images.githubusercontent.com/15201014/190388123-c4e35a7d-c32c-4d3a-9110-acb2ff2bc12f.png)

It was installed by HACS in this time

### Relevant debug logs

```text
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 2:01:10 PM (4 occurrences)
Last logged: 2:01:10 PM

Error unloading entry SUN2000-3KTL-L1 for sensor
Error unloading entry SUN2000-3KTL-L1 for number
Error unloading entry SUN2000-3KTL-L1 for switch
Error unloading entry SUN2000-3KTL-L1 for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 496, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by razvanu** [comment]
IDK, now it's working ok, after several reboots and disable/enable of the plugin.
