### ISSUE TITLE
Reading from the inverter failed - two inverters connected 

### ISSUE THREAD

**Issue by weltzien** [wlcrs/huawei_solar#147]
### System Health details

/

### Huawei Solar Setup

Port 502

IP: x.x.x.101 - SUN2000-10KTL-M1 - V100R001C00SPC146
 - Battery
 - Meter
SUN2000-4.6KTL-L1 - V200R001C00SPC124

### Describe the issue

I got only the huawei 4.6KTL, but not the 10KTL, every time i add the integration, it is not working.
the 4.6KTL i user slave ID 1.

what could be the reason for it?

### Relevant debug logs

Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py:156
First occurred: 14:27:04 (1 occurrences)
Last logged: 14:27:04

Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 347, in _do_read
    response = await self._client.protocol.read_holding_registers(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 35, in execute
    resp = await asyncio.wait_for(req, timeout=self._timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 150, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 115, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 245, in get
    return (await self.get_multiple([name], slave))[0]
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 287, in get_multiple
    response = await self._read_registers(
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 378, in _read_registers
    result = await _do_read()
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 369, in _do_read
    raise ReadException(message) from err
huawei_solar.exceptions.ReadException: Could not read register value, has another device interrupted the connection?

Logger: huawei_solar.huawei_solar
Source: custom_components/huawei_solar/config_flow.py:101
Integration: Huawei Solar
First occurred: 14:27:04 (1 occurrences)
Last logged: 14:27:04

Could not read register value, has another device interrupted the connection?

```text
2022-10-10 13:41:31.777 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [140457017138848] Sending [{"id":188,"type":"result","success":true,"result":{"resources":{"component.huawei_solar.config.abort.already_configured":"Device is already configured","component.huawei_solar.config.error.cannot_connect":"Failed to connect","component.huawei_solar.config.error.invalid_auth":"Invalid authentication","component.huawei_solar.config.error.invalid_slave_ids":"Slave IDs must be comma-separated list of ints","component.huawei_solar.config.error.read_error":"Reading from the inverter failed.","component.huawei_solar.config.error.slave_cannot_connect":"Failed to connect to additional slave","component.huawei_solar.config.error.unknown":"Unexpected error","component.huawei_solar.config.step.network_login.data.password":"Password","component.huawei_solar.config.step.network_login.data.username":"Username","component.huawei_solar.config.step.network_login.description":"Please enter the Installer credentials","component.huawei_solar.config.step.setup_network.data.enable_parameter_configuration":"Advanced: elevate permissions","component.huawei_solar.config.step.setup_network.data.host":"Host","component.huawei_solar.config.step.setup_network.data.port":"Port","component.huawei_solar.config.step.setup_network.data.slave_ids":"Slave IDs (Comma separated)","component.huawei_solar.config.step.setup_serial.data.port":"Select device","component.huawei_solar.config.step.setup_serial.data.slave_ids":"Slave IDs (Comma separated)","component.huawei_solar.config.step.setup_serial.title":"Device","component.huawei_solar.config.step.setup_serial_manual_path.data.port":"USB Device Path","component.huawei_solar.config.step.setup_serial_manual_path.title":"Path","component.huawei_solar.config.step.user.data.type":"Connection type","component.huawei_solar.config.step.user.title":"Select connection type"}}},{"id":189,"type":"result","success":true,"result":{"resources":{"component.huawei_solar.title":"Huawei Solar"}}}]
```

**Comment by wlcrs** [comment]
You need to specify the slave ids as a comma separated list.

https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-daisy-chained-inverters

Please provide screenshots of what you are submitting, and what the correct values are according to FusionSolar.

**Comment by weltzien** [comment]
Hi,
after reset the inverter because password fails, i was check the modbus ids  and found out, that i have to use: 16,1 
but this fails, till i removed the old integration of the 4.6KTL and a Homeassistant restart.

best regards

Chris
