### ISSUE TITLE
[Bug]: no data from the optimizers - since two days

### ISSUE THREAD

**Issue by etamtlosz** [wlcrs/huawei_solar#222]
### Describe the issue

Two days ago I've lost the data from my optimizers, with all its sensors becoming unavailable.

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-L1
Inverter Firmware version: V200R001C00SPC125
SDongle present: yes
Power meter present: single phase
Battery: LUNA2000 10kWh
Battery Firmware version :V100R002C00SPC116

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[config_entry-huawei_solar-afbe2edea8ac3c3adad6f0e57658de59.json.txt](https://github.com/wlcrs/huawei_solar/files/10326357/config_entry-huawei_solar-afbe2edea8ac3c3adad6f0e57658de59.json.txt)

### Upload your relevant debug logs

```text
2022-12-31 10:53:20.351 INFO (MainThread) [custom_components.huawei_solar] Cannot create optimizer sensor entities as the integration has insufficient permissions. Consider enabling elevated permissions to get more optimizer data
Traceback (most recent call last):
  File "/config/custom_components/huawei_solar/__init__.py", line 116, in async_setup_entry
    await bridge.get_optimizer_system_information_data()
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 277, in get_optimizer_system_information_data
    system_information_data = OptimizerSystemInformationDataFile(file_data)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/files.py", line 249, in __init__
    raise HuaweiSolarException("Only V102 file format is supported.")
huawei_solar.exceptions.HuaweiSolarException: Only V102 file format is supported.
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I increased the logging configuration, restarted HA, and have copied all relevant log lines from the 'Full Logs' into the textarea.

**Comment by wlcrs** [comment]
Please upgrade to the latest beta. It is solved there.
