### ISSUE TITLE
[Bug]: Issue with Capacity Control Peak Shaving

### ISSUE THREAD

**Issue by thomasdelaet** [wlcrs/huawei_solar#295]
### Describe the issue

Hey,

In latest version of huawei_solar custom component (V1.2.4) and python package (v2.2.4), I'm having issues with some battery parameters. I think this is because I'm running an older firmware (unable to upgrade) on my inverter/battery that does not support capacity control peak shaving mode. Any suggestion on how to fix?

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: not entirely sure but supports_capacity_control is False in home assistant diagnostic
SDongle present: no
Power meter present: three phase
Battery: LUNA2000 15kWh
Battery Firmware version: not entirely sure

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

{
  "home_assistant": {
    "installation_type": "Home Assistant Core",
    "version": "2023.2.5",
    "dev": false,
    "hassio": false,
    "virtualenv": true,
    "python_version": "3.10.8",
    "docker": false,
    "arch": "x86_64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "5.10.0-19-amd64",
    "run_as_root": false
  },
  "custom_components": {
    "lovelace_gen": {
      "version": "0.1.1",
      "requirements": [
        "jinja2"
      ]
    },
    "illuminance": {
      "version": "2.4.0",
      "requirements": []
    },
    "epex_spot": {
      "version": "1.0.1",
      "requirements": [
        "bs4"
      ]
    },
    "anniversaries": {
      "version": "4.5.0",
      "requirements": [
        "python-dateutil>=2.8.1",
        "integrationhelper>=0.2.2",
        "voluptuous>=0.12.1"
      ]
    },
    "google_home": {
      "version": "1.9.16",
      "requirements": [
        "glocaltokens==0.6.9"
      ]
    },
    "deebot": {
      "version": "1.5.0",
      "requirements": [
        "deebot-client==1.6.0",
        "numpy>=1.21.2"
      ]
    },
    "weather_data": {
      "version": "0.2.1",
      "requirements": [
        "xmltodict==0.12.0"
      ]
    },
    "huawei_solar": {
      "version": "1.2.4",
      "requirements": [
        "huawei-solar==2.2.4"
      ]
    },
    "dummy_thermostat": {
      "version": "1.0.0",
      "requirements": []
    },
    "mbapi2020": {
      "version": "0.8.1",
      "requirements": [
        "protobuf>=3.19.1"
      ]
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "nest_protect": {
      "version": "0.3.8",
      "requirements": []
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": []
    },
    "frigate": {
      "version": "3.0.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "huawei_solar",
    "name": "Huawei Solar",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/huawei_solar",
    "issue_tracker": "https://github.com/wlcrs/huawei_solar/issues",
    "requirements": [
      "huawei-solar==2.2.4"
    ],
    "codeowners": [
      "@wlcrs"
    ],
    "iot_class": "local_polling",
    "version": "1.2.4",
    "loggers": [
      "huawei_solar",
      "pymodbus"
    ],
    "is_built_in": false
  },
  "data": {
    "config_entry_data": {
      "host": null,
      "port": "/dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0",
      "slave_ids": [
        1
      ],
      "enable_parameter_configuration": true,
      "username": null,
      "password": null
    },
    "slave_0": {
      "model_name": "SUN2000-10KTL-M1",
      "pv_string_count": 2,
      "has_optimizers": 36,
      "battery_type": 2,
      "battery_1_type": 2,
      "battery_2_type": 0,
      "power_meter_type": 1,
      "supports_capacity_control": false
    },
    "slave_0_data": {
      "input_power": [
        559,
        "W"
      ],
      "line_voltage_A_B": [
        406.7,
        "V"
      ],
      "line_voltage_B_C": [
        405.3,
        "V"
      ],
      "line_voltage_C_A": [
        404.8,
        "V"
      ],
      "phase_A_voltage": [
        234.1,
        "V"
      ],
      "phase_B_voltage": [
        233.7,
        "V"
      ],
      "phase_C_voltage": [
        234.6,
        "V"
      ],
      "phase_A_current": [
        0.814,
        "A"
      ],
      "phase_B_current": [
        0.827,
        "A"
      ],
      "phase_C_current": [
        0.833,
        "A"
      ],
      "day_active_power_peak": [
        0,
        "W"
      ],
      "active_power": [
        559,
        "W"
      ],
      "reactive_power": [
        0,
        "VA"
      ],
      "power_factor": [
        1.0,
        null
      ],
      "grid_frequency": [
        50.03,
        "Hz"
      ],
      "efficiency": [
        92.29,
        "%"
      ],
      "internal_temperature": [
        37.2,
        "\u00b0C"
      ],
      "insulation_resistance": [
        30.0,
        "MOhm"
      ],
      "device_status": [
        "On-grid",
        null
      ],
      "fault_code": [
        0,
        null
      ],
      "startup_time": [
        "2023-02-19T08:31:59+00:00",
        null
      ],
      "shutdown_time": [
        null,
        null
      ],
      "accumulated_yield_energy": [
        12778.21,
        "kWh"
      ],
      "daily_yield_energy": [
        1.2,
        "kWh"
      ],
      "state_1": [
        [
          "Grid-Connected",
          "Grid-Connected normally"
        ],
        null
      ],
      "state_2": [
        [
          "Unlocked",
          "PV connected",
          "DSP data collection"
        ],
        null
      ],
      "state_3": [
        [
          "On-grid",
          "Off-grid switch disabled"
        ],
        null
      ],
      "alarm_1": [
        [],
        null
      ],
      "alarm_2": [
        [],
        null
      ],
      "alarm_3": [
        [],
        null
      ],
      "pv_01_voltage": [
        138.2,
        "V"
      ],
      "pv_01_current": [
        1.44,
        "A"
      ],
      "pv_02_voltage": [
        337.3,
        "V"
      ],
      "pv_02_current": [
        1.25,
        "A"
      ],
      "nb_online_optimizers": [
        36,
        null
      ],
      "grid_A_voltage": [
        234.8,
        "V"
      ],
      "grid_B_voltage": [
        234.8,
        "V"
      ],
      "grid_C_voltage": [
        234.6,
        "V"
      ],
      "active_grid_A_current": [
        -2.02,
        "I"
      ],
      "active_grid_B_current": [
        -2.33,
        "I"
      ],
      "active_grid_C_current": [
        -1.82,
        "I"
      ],
      "power_meter_active_power": [
        -975,
        "W"
      ],
      "power_meter_reactive_power": [
        569,
        "Var"
      ],
      "active_grid_power_factor": [
        -0.68,
        null
      ],
      "active_grid_frequency": [
        50.02,
        "Hz"
      ],
      "grid_exported_energy": [
        1088.81,
        "kWh"
      ],
      "grid_accumulated_energy": [
        17430.33,
        "kWh"
      ],
      "grid_accumulated_reactive_power": [
        0.0,
        "kVarh"
      ],
      "meter_type": [
        1,
        null
      ],
      "active_grid_A_B_voltage": [
        406.7,
        "V"
      ],
      "active_grid_B_C_voltage": [
        406.6,
        "V"
      ],
      "active_grid_C_A_voltage": [
        406.6,
        "V"
      ],
      "active_grid_A_power": [
        -400,
        "W"
      ],
      "active_grid_B_power": [
        -416,
        "W"
      ],
      "active_grid_C_power": [
        -158,
        "W"
      ],
      "storage_state_of_capacity": [
        4.0,
        "%"
      ],
      "storage_running_status": [
        2,
        null
      ],
      "storage_bus_voltage": [
        609.8,
        "V"
      ],
      "storage_bus_current": [
        0.1,
        "A"
      ],
      "storage_charge_discharge_power": [
        0,
        "W"
      ],
      "storage_total_charge": [
        3297.53,
        "kWh"
      ],
      "storage_total_discharge": [
        3137.05,
        "kWh"
      ],
      "storage_current_day_charge_capacity": [
        0.06,
        "kWh"
      ],
      "storage_current_day_discharge_capacity": [
        0.03,
        "kWh"
      ]
    },
    "slave_0_config_data": {
      "storage_maximum_charging_power": [
        5000,
        "W"
      ],
      "storage_maximum_discharging_power": [
        5000,
        "W"
      ],
      "storage_charging_cutoff_capacity": [
        100.0,
        "%"
      ],
      "storage_discharging_cutoff_capacity": [
        5.0,
        "%"
      ],
      "storage_working_mode_settings": [
        2,
        null
      ],
      "storage_charge_from_grid_function": [
        false,
        null
      ],
      "storage_grid_charge_cutoff_state_of_charge": [
        100.0,
        "%"
      ],
      "storage_fixed_charging_and_discharging_periods": [
        [],
        null
      ],
      "storage_power_of_charge_from_grid": [
        5000,
        "W"
      ],
      "storage_maximum_power_of_charge_from_grid": [
        10000,
        "W"
      ],
      "storage_time_of_use_charging_and_discharging_periods": [
        [
          {
            "__type": "<class 'huawei_solar.registers.HUAWEI_LUNA2000_TimeOfUsePeriod'>",
            "repr": "HUAWEI_LUNA2000_TimeOfUsePeriod(start_time=0, end_time=360, charge_flag=<ChargeFlag.CHARGE: 0>, days_effective=(True, True, True, True, True, True, True))"
          },
          {
            "__type": "<class 'huawei_solar.registers.HUAWEI_LUNA2000_TimeOfUsePeriod'>",
            "repr": "HUAWEI_LUNA2000_TimeOfUsePeriod(start_time=480, end_time=1320, charge_flag=<ChargeFlag.DISCHARGE: 1>, days_effective=(True, True, True, True, True, True, True))"
          }
        ],
        null
      ],
      "storage_excess_pv_energy_use_in_tou": [
        0,
        null
      ]
    },
    "slave_0_optimizer_data": {
      "1": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=1, output_power=32.0, voltage_to_ground=2.3, alarm=[], output_voltage=13.6, output_current=2.34, input_voltage=39.5, input_current=0.87, temperature=16.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=405.375)"
      },
      "2": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=2, output_power=34.6, voltage_to_ground=2.7, alarm=[], output_voltage=15.1, output_current=2.29, input_voltage=38.0, input_current=0.95, temperature=16.2, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=378.592)"
      },
      "3": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=3, output_power=35.7, voltage_to_ground=2.8, alarm=[], output_voltage=15.1, output_current=2.35, input_voltage=38.0, input_current=0.99, temperature=15.7, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=403.028)"
      },
      "4": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=4, output_power=34.5, voltage_to_ground=2.8, alarm=[], output_voltage=14.7, output_current=2.34, input_voltage=38.2, input_current=0.97, temperature=15.6, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=402.339)"
      },
      "5": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=5, output_power=32.5, voltage_to_ground=2.8, alarm=[], output_voltage=14.0, output_current=2.3, input_voltage=38.1, input_current=0.92, temperature=16.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=358.943)"
      },
      "6": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=6, output_power=31.5, voltage_to_ground=2.2, alarm=[], output_voltage=13.2, output_current=2.37, input_voltage=39.0, input_current=0.89, temperature=16.4, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=399.039)"
      },
      "7": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=7, output_power=32.8, voltage_to_ground=2.2, alarm=[], output_voltage=13.5, output_current=2.42, input_voltage=38.9, input_current=0.91, temperature=16.9, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=400.757)"
      },
      "8": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=8, output_power=32.7, voltage_to_ground=2.3, alarm=[], output_voltage=13.3, output_current=2.44, input_voltage=39.2, input_current=0.89, temperature=16.5, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=407.009)"
      },
      "9": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=9, output_power=34.8, voltage_to_ground=3.0, alarm=[], output_voltage=15.3, output_current=2.26, input_voltage=38.5, input_current=0.96, temperature=15.6, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=405.401)"
      },
      "10": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=10, output_power=33.8, voltage_to_ground=2.8, alarm=[], output_voltage=14.8, output_current=2.27, input_voltage=37.9, input_current=0.94, temperature=15.6, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=377.977)"
      },
      "11": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=11, output_power=33.3, voltage_to_ground=2.3, alarm=[], output_voltage=13.7, output_current=2.43, input_voltage=38.6, input_current=0.91, temperature=16.2, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=461.027)"
      },
      "12": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=12, output_power=32.2, voltage_to_ground=2.2, alarm=[], output_voltage=13.0, output_current=2.46, input_voltage=39.5, input_current=0.87, temperature=16.8, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=403.576)"
      },
      "13": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=13, output_power=33.8, voltage_to_ground=2.7, alarm=[], output_voltage=14.6, output_current=2.3, input_voltage=39.1, input_current=0.89, temperature=15.8, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=389.725)"
      },
      "14": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=14, output_power=34.3, voltage_to_ground=2.8, alarm=[], output_voltage=14.8, output_current=2.31, input_voltage=38.3, input_current=0.94, temperature=16.1, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=374.814)"
      },
      "15": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=15, output_power=32.8, voltage_to_ground=2.2, alarm=[], output_voltage=13.8, output_current=2.37, input_voltage=38.3, input_current=0.88, temperature=17.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=401.199)"
      },
      "16": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=16, output_power=34.1, voltage_to_ground=2.8, alarm=[], output_voltage=14.9, output_current=2.29, input_voltage=38.1, input_current=0.92, temperature=15.9, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=362.367)"
      },
      "17": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=17, output_power=34.0, voltage_to_ground=2.7, alarm=[], output_voltage=15.0, output_current=2.25, input_voltage=37.9, input_current=0.96, temperature=15.6, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=306.952)"
      },
      "18": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=18, output_power=33.7, voltage_to_ground=2.9, alarm=[], output_voltage=14.8, output_current=2.26, input_voltage=38.9, input_current=0.87, temperature=15.5, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=367.764)"
      },
      "19": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=19, output_power=33.5, voltage_to_ground=2.8, alarm=[], output_voltage=14.6, output_current=2.28, input_voltage=39.2, input_current=0.92, temperature=16.2, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=352.46)"
      },
      "20": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=20, output_power=33.2, voltage_to_ground=2.2, alarm=[], output_voltage=13.9, output_current=2.38, input_voltage=39.2, input_current=0.89, temperature=16.8, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=401.46)"
      },
      "21": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=21, output_power=29.9, voltage_to_ground=2.7, alarm=[], output_voltage=13.1, output_current=2.27, input_voltage=38.8, input_current=0.8, temperature=15.7, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=331.382)"
      },
      "22": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=22, output_power=32.6, voltage_to_ground=2.8, alarm=[], output_voltage=14.5, output_current=2.24, input_voltage=38.9, input_current=0.9, temperature=16.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=390.625)"
      },
      "23": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=23, output_power=32.7, voltage_to_ground=2.2, alarm=[], output_voltage=13.5, output_current=2.41, input_voltage=39.3, input_current=0.88, temperature=16.5, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=410.053)"
      },
      "24": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=24, output_power=35.2, voltage_to_ground=3.1, alarm=[], output_voltage=15.6, output_current=2.25, input_voltage=36.9, input_current=1.0, temperature=15.4, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=396.462)"
      },
      "25": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=25, output_power=32.3, voltage_to_ground=2.8, alarm=[], output_voltage=14.3, output_current=2.25, input_voltage=38.6, input_current=0.87, temperature=15.6, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=347.823)"
      },
      "26": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=26, output_power=33.5, voltage_to_ground=2.7, alarm=[], output_voltage=14.8, output_current=2.26, input_voltage=38.7, input_current=0.91, temperature=15.8, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=391.531)"
      },
      "27": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=27, output_power=33.7, voltage_to_ground=2.9, alarm=[], output_voltage=14.6, output_current=2.29, input_voltage=38.2, input_current=0.91, temperature=15.4, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=360.341)"
      },
      "28": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=28, output_power=31.1, voltage_to_ground=2.2, alarm=[], output_voltage=13.0, output_current=2.38, input_voltage=39.4, input_current=0.86, temperature=16.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=402.024)"
      },
      "29": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=29, output_power=33.6, voltage_to_ground=3.0, alarm=[], output_voltage=14.7, output_current=2.28, input_voltage=37.5, input_current=0.96, temperature=15.0, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=395.947)"
      },
      "30": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=30, output_power=35.0, voltage_to_ground=2.8, alarm=[], output_voltage=15.2, output_current=2.29, input_voltage=37.7, input_current=0.97, temperature=15.7, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=346.618)"
      },
      "31": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=31, output_power=35.0, voltage_to_ground=2.8, alarm=[], output_voltage=15.1, output_current=2.31, input_voltage=38.5, input_current=0.95, temperature=15.2, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=383.909)"
      },
      "32": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=32, output_power=34.5, voltage_to_ground=3.0, alarm=[], output_voltage=15.1, output_current=2.28, input_voltage=38.5, input_current=0.96, temperature=15.3, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=403.765)"
      },
      "33": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=33, output_power=31.1, voltage_to_ground=2.3, alarm=[], output_voltage=12.8, output_current=2.41, input_voltage=39.5, input_current=0.87, temperature=15.9, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=401.962)"
      },
      "34": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=34, output_power=34.4, voltage_to_ground=2.9, alarm=[], output_voltage=15.3, output_current=2.24, input_voltage=38.1, input_current=0.98, temperature=15.5, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=385.398)"
      },
      "35": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=35, output_power=33.5, voltage_to_ground=2.4, alarm=[], output_voltage=13.6, output_current=2.45, input_voltage=37.7, input_current=0.97, temperature=15.4, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=452.913)"
      },
      "36": {
        "__type": "<class 'huawei_solar.files.OptimizerRealTimeData'>",
        "repr": "OptimizerRealTimeData(optimizer_address=36, output_power=33.5, voltage_to_ground=2.8, alarm=[], output_voltage=14.4, output_current=2.32, input_voltage=38.2, input_current=0.93, temperature=15.8, running_status=<OptimizerRunningStatus.RUNNING: 4>, accumulated_energy_yield=374.183)"
      }
    }
  }
}

### Upload your relevant debug logs

```text
2023-02-19 10:10:00.807 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/api/__init__.py", line 325, in post
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/number/__init__.py", line 96, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/home/homeassistant/.homeassistant/custom_components/huawei_solar/number.py", line 280, in async_set_native_value
    await self.coordinator.async_request_refresh()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 189, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 215, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/huawei_solar/number.py", line 266, in _handle_coordinator_update
    max_register = self.coordinator.data[
KeyError: 'storage_capacity_control_soc_peak_shaving'
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by thomasdelaet** [comment]
I think I found the issue:

In number.py file, the dynamic_maximum_key is used in the definition of rn.STORAGE_DISCHARGING_CUTOFF_CAPACITY (line 81). Deleting this solves the issue.

Given that dynamic_maxim_key seems to depend on peak shaving functionality, I don't think it should be there.
