### ISSUE TITLE
[Bug]: Error during updates of power meter registers

### ISSUE THREAD

**Issue by nalla** [wlcrs/huawei_solar#308]
### Describe the issue

I see the following error in the home assistant logs. Seems like a some data type issue when no data is available? As it states the "NoneType" is tried to put into a `abs()` function.

~~~
This error originated from a custom integration.

Logger: custom_components.huawei_solar
Source: custom_components/huawei_solar/__init__.py:309
Integration: Huawei Solar
First occurred: 13:08:22 (5 occurrences)
Last logged: 13:09:02

Unexpected error fetching BTXXXXXXXXXX_data_update_coordinator data: bad operand type for abs(): 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/huawei_solar/__init__.py", line 309, in _async_update_data
    return await self.bridge.update()
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 168, in update
    result.update(await self._get_multiple_to_dict(POWER_METER_REGISTERS))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/bridge.py", line 152, in _get_multiple_to_dict
    return dict(zip(names, await self.client.get_multiple(names, self.slave_id)))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 248, in get_multiple
    result.append(await self._decode_response(registers[idx], decoder))
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 197, in _decode_response
    result = reg.decode(decoder, self)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/registers.py", line 207, in decode
    return abs(super().decode(decoder, inverter))
TypeError: bad operand type for abs(): 'NoneType'

~~~

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-4KTL-M1
Inverter Firmware version: 151
SDongle present: yes
Power meter present: three phase
Battery: LUNA2000 5kWh
Battery Firmware version: 118

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

~~~
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.2.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.0-60-generic",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "huawei_solar": {
      "version": "1.2.4",
      "requirements": [
        "huawei-solar==2.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "huawei_solar",
    "name": "Huawei Solar",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/huawei_solar",
    "issue_tracker": "https://github.com/wlcrs/huawei_solar/issues",
    "requirements": [
      "huawei-solar==2.2.4"
    ],
    "codeowners": [
      "@wlcrs"
    ],
    "iot_class": "local_polling",
    "version": "1.2.4",
    "loggers": [
      "huawei_solar",
      "pymodbus"
    ],
    "is_built_in": false
  },
  "data": {
    "config_entry_data": {
      "host": "192.168.200.1",
      "port": 6607,
      "slave_ids": [
        0
      ],
      "enable_parameter_configuration": true,
      "username": "installer",
      "password": "**REDACTED**"
    },
    "slave_0": {
      "model_name": "SUN2000-4KTL-M1\u0000SUN2000-5KTL-M",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 2,
      "battery_1_type": 2,
      "battery_2_type": 0,
      "power_meter_type": 1,
      "supports_capacity_control": true
    },
    "slave_0_data": {
      "input_power": [
        2909,
        "W"
      ],
      "line_voltage_A_B": [
        409.8,
        "V"
      ],
      "line_voltage_B_C": [
        408.6,
        "V"
      ],
      "line_voltage_C_A": [
        407.0,
        "V"
      ],
      "phase_A_voltage": [
        236.0,
        "V"
      ],
      "phase_B_voltage": [
        235.9,
        "V"
      ],
      "phase_C_voltage": [
        235.6,
        "V"
      ],
      "phase_A_current": [
        4.139,
        "A"
      ],
      "phase_B_current": [
        4.155,
        "A"
      ],
      "phase_C_current": [
        4.172,
        "A"
      ],
      "day_active_power_peak": [
        4400,
        "W"
      ],
      "active_power": [
        2909,
        "W"
      ],
      "reactive_power": [
        -10,
        "VA"
      ],
      "power_factor": [
        1.0,
        null
      ],
      "grid_frequency": [
        49.98,
        "Hz"
      ],
      "efficiency": [
        100.0,
        "%"
      ],
      "internal_temperature": [
        48.6,
        "\u00b0C"
      ],
      "insulation_resistance": [
        30.0,
        "MOhm"
      ],
      "device_status": [
        "On-grid",
        null
      ],
      "fault_code": [
        0,
        null
      ],
      "startup_time": [
        "2023-02-28T07:48:31+00:00",
        null
      ],
      "shutdown_time": [
        null,
        null
      ],
      "accumulated_yield_energy": [
        154.13,
        "kWh"
      ],
      "daily_yield_energy": [
        9.02,
        "kWh"
      ],
      "state_1": [
        [
          "Grid-Connected",
          "Grid-Connected normally"
        ],
        null
      ],
      "state_2": [
        [
          "Unlocked",
          "PV connected",
          "DSP data collection"
        ],
        null
      ],
      "state_3": [
        [
          "On-grid",
          "Off-grid switch disabled"
        ],
        null
      ],
      "alarm_1": [
        [],
        null
      ],
      "alarm_2": [
        [],
        null
      ],
      "alarm_3": [
        [],
        null
      ],
      "pv_01_voltage": [
        418.5,
        "V"
      ],
      "pv_01_current": [
        7.29,
        "A"
      ],
      "pv_02_voltage": [
        0.0,
        "V"
      ],
      "pv_02_current": [
        0.0,
        "A"
      ],
      "grid_A_voltage": [
        236.0,
        "V"
      ],
      "grid_B_voltage": [
        235.6,
        "V"
      ],
      "grid_C_voltage": [
        235.8,
        "V"
      ],
      "active_grid_A_current": [
        3.62,
        "I"
      ],
      "active_grid_B_current": [
        3.73,
        "I"
      ],
      "active_grid_C_current": [
        3.89,
        "I"
      ],
      "power_meter_active_power": [
        2638,
        "W"
      ],
      "power_meter_reactive_power": [
        136,
        "Var"
      ],
      "active_grid_power_factor": [
        -0.992,
        null
      ],
      "active_grid_frequency": [
        49.97,
        "Hz"
      ],
      "grid_exported_energy": [
        28.15,
        "kWh"
      ],
      "grid_accumulated_energy": [
        583.21,
        "kWh"
      ],
      "grid_accumulated_reactive_power": [
        0.0,
        "kVarh"
      ],
      "meter_type": [
        1,
        null
      ],
      "active_grid_A_B_voltage": [
        408.3,
        "V"
      ],
      "active_grid_B_C_voltage": [
        408.2,
        "V"
      ],
      "active_grid_C_A_voltage": [
        408.6,
        "V"
      ],
      "active_grid_A_power": [
        848,
        "W"
      ],
      "active_grid_B_power": [
        876,
        "W"
      ],
      "active_grid_C_power": [
        914,
        "W"
      ],
      "storage_state_of_capacity": [
        100.0,
        "%"
      ],
      "storage_running_status": [
        2,
        null
      ],
      "storage_bus_voltage": [
        786.0,
        "V"
      ],
      "storage_bus_current": [
        0.0,
        "A"
      ],
      "storage_charge_discharge_power": [
        0,
        "W"
      ],
      "storage_total_charge": [
        105.31,
        "kWh"
      ],
      "storage_total_discharge": [
        95.55,
        "kWh"
      ],
      "storage_current_day_charge_capacity": [
        5.62,
        "kWh"
      ],
      "storage_current_day_discharge_capacity": [
        2.01,
        "kWh"
      ]
    },
    "slave_0_config_data": {
      "storage_maximum_charging_power": [
        2500,
        "W"
      ],
      "storage_maximum_discharging_power": [
        2500,
        "W"
      ],
      "storage_charging_cutoff_capacity": [
        100.0,
        "%"
      ],
      "storage_discharging_cutoff_capacity": [
        5.0,
        "%"
      ],
      "storage_working_mode_settings": [
        2,
        null
      ],
      "storage_charge_from_grid_function": [
        true,
        null
      ],
      "storage_grid_charge_cutoff_state_of_charge": [
        20.0,
        "%"
      ],
      "storage_fixed_charging_and_discharging_periods": [
        [],
        null
      ],
      "storage_power_of_charge_from_grid": [
        4400,
        "W"
      ],
      "storage_maximum_power_of_charge_from_grid": [
        4400,
        "W"
      ],
      "storage_time_of_use_charging_and_discharging_periods": [
        [
          {
            "__type": "<class 'huawei_solar.registers.HUAWEI_LUNA2000_TimeOfUsePeriod'>",
            "repr": "HUAWEI_LUNA2000_TimeOfUsePeriod(start_time=0, end_time=360, charge_flag=<ChargeFlag.CHARGE: 0>, days_effective=(True, True, True, True, True, True, True))"
          },
          {
            "__type": "<class 'huawei_solar.registers.HUAWEI_LUNA2000_TimeOfUsePeriod'>",
            "repr": "HUAWEI_LUNA2000_TimeOfUsePeriod(start_time=480, end_time=1320, charge_flag=<ChargeFlag.DISCHARGE: 1>, days_effective=(True, True, True, True, True, True, True))"
          }
        ],
        null
      ],
      "storage_excess_pv_energy_use_in_tou": [
        0,
        null
      ],
      "storage_capacity_control_mode": [
        0,
        null
      ],
      "storage_capacity_control_soc_peak_shaving": [
        50.0,
        "%"
      ],
      "storage_capacity_control_periods": [
        [],
        null
      ]
    }
  }
}
~~~

### Upload your relevant debug logs

```text
None
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by nalla** [comment]
That was fast :) Will close for now. And will monitor the situation with 1.2.5.
