### ISSUE TITLE
[Bug]: Sensors cannot be added to dashboard

### ISSUE THREAD

**Issue by luotinen** [wlcrs/huawei_solar#326]
### Describe the issue

After adding the intergration, sensors appear for the device. Upon clicking the "Add to dashboard" button the following error is produced: "You don't seem to be in control of any dashboard, please take control first."

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: V100R001C00SPC150
SDongle present: yes
Power meter present: three phase
Battery:  No
Battery Firmware version: N/A

### How do you connect to the inverter?

Via the SDongle, wireless connection

### Upload your Diagnostics File

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Helsinki",
    "os_name": "Linux",
    "os_version": "5.15.84-v8",
    "supervisor": "2023.03.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "huawei_solar": {
      "version": "1.2.4",
      "requirements": [
        "huawei-solar==2.2.4"
      ]
    },
    "pax_ble": {
      "version": "1.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "daikin_residential": {
      "version": "2.3.0",
      "requirements": [
        "oic==1.4.0"
      ]
    },
    "nordpool": {
      "version": "0.0.11",
      "requirements": [
        "nordpool>=0.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "huawei_solar",
    "name": "Huawei Solar",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/huawei_solar",
    "issue_tracker": "https://github.com/wlcrs/huawei_solar/issues",
    "requirements": [
      "huawei-solar==2.2.4"
    ],
    "codeowners": [
      "@wlcrs"
    ],
    "iot_class": "local_polling",
    "version": "1.2.4",
    "loggers": [
      "huawei_solar",
      "pymodbus"
    ],
    "is_built_in": false
  },
  "data": {
    "config_entry_data": {
      "host": "192.168.68.128",
      "port": 502,
      "slave_ids": [
        1
      ],
      "enable_parameter_configuration": false,
      "username": null,
      "password": null
    },
    "slave_0": {
      "model_name": "SUN2000-10KTL-M1\u0000\u0000\u0000\u0000SUN2000-12",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 0,
      "battery_1_type": 0,
      "battery_2_type": 0,
      "power_meter_type": null,
      "supports_capacity_control": false
    },
    "slave_0_data": {
      "input_power": [
        3477,
        "W"
      ],
      "line_voltage_A_B": [
        406.6,
        "V"
      ],
      "line_voltage_B_C": [
        406.1,
        "V"
      ],
      "line_voltage_C_A": [
        408.2,
        "V"
      ],
      "phase_A_voltage": [
        235.5,
        "V"
      ],
      "phase_B_voltage": [
        234.1,
        "V"
      ],
      "phase_C_voltage": [
        235.2,
        "V"
      ],
      "phase_A_current": [
        4.814,
        "A"
      ],
      "phase_B_current": [
        4.863,
        "A"
      ],
      "phase_C_current": [
        4.869,
        "A"
      ],
      "day_active_power_peak": [
        5108,
        "W"
      ],
      "active_power": [
        3389,
        "W"
      ],
      "reactive_power": [
        0,
        "VA"
      ],
      "power_factor": [
        1.0,
        null
      ],
      "grid_frequency": [
        50.04,
        "Hz"
      ],
      "efficiency": [
        97.47,
        "%"
      ],
      "internal_temperature": [
        27.3,
        "\u00b0C"
      ],
      "insulation_resistance": [
        30.0,
        "MOhm"
      ],
      "device_status": [
        "On-grid",
        null
      ],
      "fault_code": [
        0,
        null
      ],
      "startup_time": [
        "2023-03-17T04:32:05+00:00",
        null
      ],
      "shutdown_time": [
        "2023-03-16T16:30:40+00:00",
        null
      ],
      "accumulated_yield_energy": [
        453.09,
        "kWh"
      ],
      "daily_yield_energy": [
        8.45,
        "kWh"
      ],
      "state_1": [
        [
          "Grid-Connected",
          "Grid-Connected normally"
        ],
        null
      ],
      "state_2": [
        [
          "Unlocked",
          "PV connected",
          "DSP data collection"
        ],
        null
      ],
      "state_3": [
        [
          "On-grid",
          "Off-grid switch disabled"
        ],
        null
      ],
      "alarm_1": [
        [],
        null
      ],
      "alarm_2": [
        [],
        null
      ],
      "alarm_3": [
        [],
        null
      ],
      "pv_01_voltage": [
        387.5,
        "V"
      ],
      "pv_01_current": [
        4.72,
        "A"
      ],
      "pv_02_voltage": [
        354.8,
        "V"
      ],
      "pv_02_current": [
        4.65,
        "A"
      ]
    }
  }
}

### Upload your relevant debug logs

```text
2023-03-17 10:11:12.372 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 43006
2023-03-17 10:11:12.372 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:12.373 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:12.374 DEBUG (MainThread) [huawei_solar.huawei_solar] Backing off reading for 1.0 seconds after 1 tries
2023-03-17 10:11:13.375 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:13.376 INFO (MainThread) [backoff] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:13.377 DEBUG (MainThread) [huawei_solar.huawei_solar] Backing off reading for 2.0 seconds after 2 tries
2023-03-17 10:11:14.364 WARNING (MainThread) [pymodbus.logging] Failed to connect: [Errno 113] Connect call failed ('192.168.1.128', 502)
2023-03-17 10:11:15.379 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:15.380 INFO (MainThread) [backoff] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:15.380 DEBUG (MainThread) [huawei_solar.huawei_solar] Backing off reading for 4.0 seconds after 3 tries
2023-03-17 10:11:19.365 WARNING (MainThread) [pymodbus.logging] Failed to connect: [Errno 113] Connect call failed ('192.168.1.128', 502)
2023-03-17 10:11:19.382 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:19.383 INFO (MainThread) [backoff] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:19.383 DEBUG (MainThread) [huawei_solar.huawei_solar] Backing off reading for 8.0 seconds after 4 tries
2023-03-17 10:11:26.365 WARNING (MainThread) [pymodbus.logging] Failed to connect: [Errno 113] Connect call failed ('192.168.1.128', 502)
2023-03-17 10:11:27.384 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:27.385 INFO (MainThread) [backoff] Backing off _do_read(...) for 16.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:27.386 DEBUG (MainThread) [huawei_solar.huawei_solar] Backing off reading for 16.0 seconds after 5 tries
2023-03-17 10:11:37.365 WARNING (MainThread) [pymodbus.logging] Failed to connect: [Errno 113] Connect call failed ('192.168.1.128', 502)
2023-03-17 10:11:43.387 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-03-17 10:11:43.388 ERROR (MainThread) [backoff] Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-03-17 10:11:43.393 ERROR (MainThread) [huawei_solar.huawei_solar] Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 284, in _do_read
    raise ConnectionInterruptedException(message)
huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 127, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 89, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 205, in get
    return (await self.get_multiple([name], slave))[0]
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 240, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 318, in _read_registers
    result = await _do_read()
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 159, in retry
    await _call_handlers(on_giveup, **details, exception=e)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 37, in _call_handlers
    await handler(details)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 16, in f
    return coro_or_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py", line 266, in backoff_giveup
    raise ReadException(f"Failed to read register {register} after {details['tries']} tries")
huawei_solar.exceptions.ReadException: Failed to read register 43006 after 6 tries
2023-03-17 10:12:55.876 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 43006
2023-03-17 10:12:56.246 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47000
2023-03-17 10:12:56.797 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30000
2023-03-17 10:12:56.974 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30071
2023-03-17 10:12:57.356 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37200
2023-03-17 10:12:57.866 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100
2023-03-17 10:12:58.168 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47000
2023-03-17 10:12:58.275 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47089
2023-03-17 10:12:59.583 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 43006
2023-03-17 10:12:59.879 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47000
2023-03-17 10:13:00.158 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30000
2023-03-17 10:13:00.545 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 30071
2023-03-17 10:13:01.118 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37200
2023-03-17 10:13:01.713 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100
2023-03-17 10:13:02.611 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47000
2023-03-17 10:13:03.554 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 47089
2023-03-17 10:13:03.854 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:13:04.070 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:13:04.473 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:13:05.099 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:13:15.464 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:13:15.983 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:13:46.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:13:46.478 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:14:16.194 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:14:16.580 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:14:46.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:14:46.542 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:15:16.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:15:16.450 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:15:47.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:15:47.520 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:16:17.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:16:17.710 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:16:48.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:16:49.069 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:17:19.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:17:19.410 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:17:50.194 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:17:50.649 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:18:20.193 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:18:20.573 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:18:51.194 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:18:51.426 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
2023-03-17 10:19:21.194 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064
2023-03-17 10:19:21.430 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
That error is unrelated to this integration. Check the account permissions in your HA.

**Comment by luotinen** [comment]
This is my only integration which is unable to add sensors to UI controlled dashboard. I interpret that this is the intended behaviour.

If someone else is trying to add sensors, you need to go to the dashboard you want to take control, click on the three dots on top right and take control. After this, the UI will no longer keep the dashboard up-to-date and you will have to manually add the items you want to see.
