### ISSUE TITLE
[Bug]: Can`t add the integration

### ISSUE THREAD

**Issue by renatod47** [wlcrs/huawei_solar#447]
### Describe the issue

Since 1.2.6 it stopped working. 
I changed the PyModbus to a certain version but then it stopped working again. 
I deleted the integration and now I can't even add it because it fails to connect via rs485 -> USB 

### Bescribe your Huawei Solar Setup

Inverter Type: Huawei 30KTL
Inverter Firmware version: Latest
SDongle present: no
Power meter present: no
Battery: None

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

This is the only thing i can get
![image](https://github.com/wlcrs/huawei_solar/assets/135228664/63191b27-16cf-409b-9ab4-4fc034dca85b)

### Upload your relevant debug logs

```text
2023-08-16 16:52:26.051 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-08-16 16:52:26.052 ERROR (MainThread) [backoff] Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-08-16 16:52:26.071 ERROR (MainThread) [huawei_solar.huawei_solar] Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 349, in _do_read
    raise ConnectionInterruptedException(message)
huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 210, in create_rtu
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 276, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 398, in _read_registers
    return await _do_read()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 159, in retry
    await _call_handlers(on_giveup, **details, exception=e)
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 37, in _call_handlers
    await handler(details)
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 16, in f
    return coro_or_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 327, in backoff_giveup
    raise ReadException(f"Failed to read register {register} after {details['tries']} tries")
huawei_solar.exceptions.ReadException: Failed to read register 43006 after 6 tries
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by sephiroth1395** [comment]
I have the same problem since a few days, running 1.2.6 over Hassio and connecting via WiFi to the internal AP (I'm in close range, never got the SDongle-A05 to work with the integration but that's another topic).

It's really weird, I did a tcpdump to try and understand things better and after the TCP connection is established nothing happens anymore.  The protocol decoder of Wireshark doesn't even detect Modbus TCP traffic.

**Comment by renatod47** [comment]
Update:
With this config, I put it functional: 
Home Assistant OS -> 10.3
Home Assistant Core -> 2023.7.0
Huawei Solar -> 1.2.5 -> 2.2.6
PymodBus -> 3.2.0

**Comment by renatod47** [comment]
Update: 
(or maybe not) 
With this exact config, it stopped working today after I rebooted the system.

**Comment by wlcrs** [comment]
This looks like a connectivity problem. I cannot help you with that.
