### ISSUE TITLE
[Bug]: "Failed to Connect" after upgrade 2023.8.2

### ISSUE THREAD

**Issue by zsgodor** [wlcrs/huawei_solar#448]
### Describe the issue

My system is Debian 11 HA running with docker without SuperVisor.
If you have more information please feel free.
I dont know what can i do, downgrade an early version 2023.8.1?
After I upgraded HA version 2023.8.2, the integration does't work. The integration is (1.2.6)
I deleted and re-add the integration, i upgrade the manifest.json (["huawei-solar==2.2.8", "pyModbus==3.2.2"],) but the integration is not work, I chek the inverter connection, i connect a wifi usb key my hass client machine, the inverter inside wifi network it name is "SUN2000-HV20C0067666" I ping 192.168.200.1 
wlx000f00acd96d: connected to SUN2000-HV20C0067666
        "Ralink MT7601U"
        wifi (mt7601u), 00:0F:00:AC:D9:6D, hw, mtu 1500
        ip4 default
        inet4 192.168.200.100/24
        route4 0.0.0.0/0
        route4 192.168.200.0/24
        inet6 fe80::c315:9434:1acd:7727/64
        route6 fe80::/64
root@hassnas:~# ping 192.168.200.1
PING 192.168.200.1 (192.168.200.1) 56(84) bytes of data.
64 bytes from 192.168.200.1: icmp_seq=1 ttl=255 time=116 ms
64 bytes from 192.168.200.1: icmp_seq=2 ttl=255 time=56.4 ms

        
![Képernyőfotó 2023-08-17 - du  2 20 56](https://github.com/wlcrs/huawei_solar/assets/64435192/321ffa3d-b013-49c6-831e-d2838c437648)

### Bescribe your Huawei Solar Setup

Inverter Type:SUN2000-15KTL-M2
Inverter Firmware version: V100R001C00SPC153
SDongle present: yes  SDongleA-05. V100R001C00SPC117
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Logger: pymodbus.logging
Source: runner.py:179
First occurred: du. 3:33:24 (142 occurrences)
Last logged: du. 4:38:43

Failed to connect: [Errno 111] Connect call failed ('192.168.200.1', 502)
Failed to connect:
Ignoring launch of delayed reconnection, another is in progress
Failed to connect: [Errno 111] Connect call failed ('192.168.88.86', 502)

### Upload your relevant debug logs

```text
Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py:143
First occurred: du. 3:33:28 (9 occurrences)
Last logged: du. 4:38:27

Timeout while waiting for connection. Reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
-----------------------------------------------------------------------------------------------
Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py:184
First occurred: du. 3:33:28 (9 occurrences)
Last logged: du. 4:38:27

Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 178, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 276, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 396, in _read_registers
    async with self._communication_lock():
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 145, in _communication_lock
    raise err
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by zsgodor** [comment]
2023-08-17 15:06:34.628 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:34.628 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:34.628 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:35.630 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:35.646 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:35.647 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:35.647 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:35.647 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:35.786 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:35.786 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:35.786 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:36.787 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:36.792 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:36.792 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:36.793 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:36.793 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:36.906 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:36.906 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:36.907 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:36.919 DEBUG (MainThread) [pymodbus.logging] Current transaction state - TRANSACTION_COMPLETE
2023-08-17 15:06:36.919 DEBUG (MainThread) [pymodbus.logging] Running transaction 23
2023-08-17 15:06:36.919 DEBUG (MainThread) [pymodbus.logging] SEND: 0x0 0x17 0x0 0x0 0x0 0x6 0x1 0x3 0x0 0x0 0x0 0x26
2023-08-17 15:06:36.919 DEBUG (MainThread) [pymodbus.logging] New Transaction state "SENDING"
2023-08-17 15:06:36.920 DEBUG (MainThread) [pymodbus.logging] Changing transaction state from "SENDING" to "WAITING FOR REPLY"
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Changing transaction state from "WAITING FOR REPLY" to "PROCESSING REPLY"
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] RECV: 0x0 0x17 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x5b 0xff 0x0 0x78 0xff 0xff 0xff 0x13 0x0 0x29 0x97 0xc5 0x0 0x7b 0xeb 0xc 0x3 0x44 0x0 0x0 0x5b 0xeb 0x0 0x56 0xff 0xff 0xff 0xc7 0x0 0x47 0xde 0x8 0x0 0x69 0x79 0x3a 0x1 0x21 0x0 0x0 0x5a 0xa8 0x0 0x98 0xff 0xff 0xfe 0xb1 0x0 0x40 0xef 0x36 0x0 0x7b 0x74 0x36 0x3 0xb3 0x0 0x0 0x13 0x87 0x0 0x0 0xff 0xff 0xfd 0x8b 0x0 0xa2 0xe5 0x6 0x1 0x51 0x58 0xf9
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x17 0x0 0x0 0x0 0x4f 0x1 0x3 0x4c 0x5b 0xff 0x0 0x78 0xff 0xff 0xff 0x13 0x0 0x29 0x97 0xc5 0x0 0x7b 0xeb 0xc 0x3 0x44 0x0 0x0 0x5b 0xeb 0x0 0x56 0xff 0xff 0xff 0xc7 0x0 0x47 0xde 0x8 0x0 0x69 0x79 0x3a 0x1 0x21 0x0 0x0 0x5a 0xa8 0x0 0x98 0xff 0xff 0xfe 0xb1 0x0 0x40 0xef 0x36 0x0 0x7b 0x74 0x36 0x3 0xb3 0x0 0x0 0x13 0x87 0x0 0x0 0xff 0xff 0xfd 0x8b 0x0 0xa2 0xe5 0x6 0x1 0x51 0x58 0xf9
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Adding transaction 23
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Getting transaction 23
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] [23551, 120, 65535, 65299, 41, 38853, 123, 60172, 836, 0, 23531, 86, 65535, 65479, 71, 56840, 105, 31034, 289, 0, 23208, 152, 65535, 65201, 64, 61238, 123, 29750, 947, 0, 4999, 0, 65535, 64907, 162, 58630, 337, 22777]
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff\x13']
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00)', b'\x97\xc5']
2023-08-17 15:06:36.998 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00{', b'\xeb\x0c']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff\xc7']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00G', b'\xde\x08']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00i', b'y:']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe\xb1']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00@', b'\xef6']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00{', b't6']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfd\x8b']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\xa2', b'\xe5\x06']
2023-08-17 15:06:36.999 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x01Q', b'X\xf9']
2023-08-17 15:06:37.907 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:37.915 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:37.915 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:37.916 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:37.916 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:38.014 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:38.014 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:38.014 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:39.015 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:39.020 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:39.020 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:39.020 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:39.021 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:39.159 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:39.159 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:39.160 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:39.322 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:39.329 WARNING (MainThread) [pymodbus.logging] Failed to connect: [Errno 111] Connect call failed ('192.168.200.1', 502)
2023-08-17 15:06:39.332 DEBUG (MainThread) [pymodbus.logging] Waiting 300000 ms before next connection attempt.
2023-08-17 15:06:39.945 WARNING (Thread-5) [pychromecast.socket_client] [Konyha(192.168.88.230):8009] Heartbeat timeout, resetting connection
2023-08-17 15:06:40.161 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:40.173 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:40.173 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:40.173 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:40.174 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:40.308 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:40.308 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:40.308 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:41.309 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:41.325 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:41.325 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:41.325 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:41.325 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:41.446 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:41.446 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:41.446 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.
2023-08-17 15:06:42.447 DEBUG (MainThread) [pymodbus.logging] Connecting.
2023-08-17 15:06:42.450 DEBUG (MainThread) [pymodbus.logging] Client connected to modbus server
2023-08-17 15:06:42.451 INFO (MainThread) [pymodbus.logging] Protocol made connection.
2023-08-17 15:06:42.451 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-08-17 15:06:42.451 INFO (MainThread) [pymodbus.logging] Connected to 192.168.200.1:6607.
2023-08-17 15:06:42.561 INFO (MainThread) [pymodbus.logging] Protocol lost connection.
2023-08-17 15:06:42.561 DEBUG (MainThread) [pymodbus.logging] Client disconnected from modbus server: None
2023-08-17 15:06:42.561 DEBUG (MainThread) [pymodbus.logging] Waiting 1000 ms before next connection attempt.

**Comment by zsgodor** [comment]
Ez a hiba egy egyéni integrációból lett származtatva.

Logger: huawei_solar.huawei_solar
Source: custom_components/huawei_solar/__init__.py:87
Integration: Huawei Solar (documentation, issues)
First occurred: du. 4:58:31 (77 occurrences)
Last logged: du. 6:22:58

Could not read register value, has another device interrupted the connection?

**Comment by zsgodor** [comment]
Logger: py.warnings
Source: runner.py:179
First occurred: du. 4:58:07 (3 occurrences)
Last logged: du. 6:22:54

/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py:228: RuntimeWarning: coroutine 'AsyncModbusTcpClient.close' was never awaited self._client.close()

**Comment by zsgodor** [comment]
Ez a hiba egy egyéni integrációból lett származtatva.

Logger: backoff
Source: custom_components/huawei_solar/__init__.py:87
Integration: Huawei Solar (documentation, issues)
First occurred: du. 4:59:04 (23 occurrences)
Last logged: du. 5:32:20

Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Could not read register value, has another device interrupted the connection?)

**Comment by zsgodor** [comment]
Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py:184
First occurred: du. 4:59:04 (21 occurrences)
Last logged: du. 5:32:20

Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 349, in _do_read
    raise ConnectionInterruptedException(message)
huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 178, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 276, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 398, in _read_registers
    return await _do_read()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 159, in retry
    await _call_handlers(on_giveup, **details, exception=e)
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 37, in _call_handlers
    await handler(details)
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 16, in f
    return coro_or_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 327, in backoff_giveup
    raise ReadException(f"Failed to read register {register} after {details['tries']} tries")
huawei_solar.exceptions.ReadException: Failed to read register 43006 after 6 tries

**Comment by zsgodor** [comment]
I think the problem my  weak WIFI connection, the wifi always reconnecting, and duplicate the connection.
I fixed this problem, now the integration is connect the inverter, and working.
