### ISSUE TITLE
[Bug]: Direct connection to Inverter AP broken

### ISSUE THREAD

**Issue by einwaschdl** [wlcrs/huawei_solar#471]
### Describe the issue

In my main HA Instance I initially set up the integration via a WLAN Dongle directly attached to the HA server and by connecting to the integrated Hotspot "SUN2000-*" Wifi. I had connection issues because of the distance between inverter and my server so I switched to the connection using the SDongle, which works as expected currently. After buying an USB extension cord I wanted to switch back to the direct connection, but I am not able to add the inverter that way anymore.

To test it further and to avoid left overs, I installed a new HA vm and tried it with that. I get the same error, like on my main System, when I try to create a direct connection. I can ping the IP of the inverter and the connection is stable, but while adding the inverter I get an error.

No clue why it worked once 4 weeks ago, when i started the inverter for the first time. I also tried the last three versions 1.2.5, 1.2.6 and 1.2.7 without luck. I have also disconnected the inverter from AC and DC power for 5 minutes...nothing helps.

Additional note: My inverter is quite new (M5) and the integrated wifi uses the IP 192.168.8.1/24 in contrast to the documentation. 

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-12KTL-M5
Inverter Firmware version: V200R022C10SPC103
SDongle present: yes
Power meter present: three phase
Battery:  None
Battery Firmware version: -

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Diagnostic file is not available, as I can not add the inverter.

### Upload your relevant debug logs

```text
2023-09-14 11:25:06.852 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-14 11:25:06.853 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-14 11:29:00.935 DEBUG (MainThread) [pymodbus.logging] Connecting to 192.168.8.1:6607.
2023-09-14 11:29:00.936 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-09-14 11:29:00.939 DEBUG (MainThread) [pymodbus.logging] Connected to comm
2023-09-14 11:29:00.940 DEBUG (MainThread) [pymodbus.logging] callback_connected called
2023-09-14 11:29:00.940 DEBUG (MainThread) [huawei_solar.modbus] Waiting for 1500 milliseconds after connection before performing operations
2023-09-14 11:29:00.942 INFO (MainThread) [huawei_solar.huawei_solar] Waiting for connection ...
2023-09-14 11:29:02.442 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 43006 with length 1 from slave 0
2023-09-14 11:29:02.443 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0xa7 0xfe 0x0 0x1
2023-09-14 11:29:02.443 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-09-14 11:29:12.445 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0xa7 0xfe 0x0 0x1
2023-09-14 11:29:12.445 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-09-14 11:29:22.447 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0xa7 0xfe 0x0 0x1
2023-09-14 11:29:22.447 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-09-14 11:29:32.449 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0xa7 0xfe 0x0 0x1
2023-09-14 11:29:32.450 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-09-14 11:29:42.452 DEBUG (MainThread) [pymodbus.logging] Connection lost comm due to Server not responding
2023-09-14 11:29:42.452 DEBUG (MainThread) [pymodbus.logging] Getting transaction 1
2023-09-14 11:29:42.453 ERROR (MainThread) [huawei_solar.huawei_solar] Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 178, in create
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 276, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 398, in _read_registers
    return await _do_read()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 351, in _do_read
    response = await self._client.read_holding_registers(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/base.py", line 210, in async_execute
    raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [x] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
The logs show that the inverter does not respond to queries from the integration. There is nothing that I can do to fix that as this is not a bug in this integration.
