### ISSUE TITLE
[Bug]: Integration won't start

### ISSUE THREAD

**Issue by xm4rcell0x** [wlcrs/huawei_solar#473]
### Describe the issue

today morning i found that huawei solar didn't work at all. I tried to upgraded ha core to 9.2 and the integration to the very latest but nothing has changed

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: last one
SDongle present: no
Power meter present: three phase
Battery:LUNA2000 20kWh
Battery Firmware version: last one

### How do you connect to the inverter?

Over serial, with a serial-to-USB stick

### Upload your Diagnostics File

can not download because the integration doesn't work

here the debug log
[home-assistant_huawei_solar_2023-09-14T14-52-59.813Z.log](https://github.com/wlcrs/huawei_solar/files/12610417/home-assistant_huawei_solar_2023-09-14T14-52-59.813Z.log)

### Upload your relevant debug logs

```text
already uploaded
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by marcgeurts** [comment]
I'm having the same issue since the latest update

**Comment by xm4rcell0x** [comment]
Thanks, I was struggling with the usb to rs485 converter thinking that it was broken 😅

**Comment by xm4rcell0x** [comment]
[home-assistant_2023-09-14T15-41-14.260Z.log](https://github.com/wlcrs/huawei_solar/files/12610793/home-assistant_2023-09-14T15-41-14.260Z.log)

**Comment by renatod47** [comment]
https://github.com/wlcrs/huawei_solar/issues/447
Im having this same problem a long time ago 
Latest days i get it to work and even after the update it was functioning 
Since today 11AM it stoped working at all

**Comment by xm4rcell0x** [comment]
I just read #447 and saw that @wlcrs  can't do anything. What do we do?

**Comment by renatod47** [comment]
> I just read #447 and saw that @wlcrs  can't do anything. What do we do?

I already downgrade versions and did a lot of things that stop working momentarily, because after a while it returns to the same. Or because some update, I don't know at all.
I would do anything to help as this directly interferes with my work

**Comment by xm4rcell0x** [comment]
Can you tell me what huawei_solar version have you downgraded ? HA Core 9.2? 
Thank you 🙏

**Comment by renatod47** [comment]
> Can you tell me what huawei_solar version have you downgraded ? HA Core 9.2? 
> Thank you 🙏 

You have everything on #447 
You re welcome

**Comment by wlcrs** [comment]
What is the device from the following error which keeps on appearing in your logs:

```
Failed to connect [Errno 2] could not open port /dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0'
```

Please add a diagnostics file to this report to make my life easier:

![image](https://github.com/wlcrs/huawei_solar/assets/2150060/e0eaef80-79f3-4198-b3a1-51f2d8f2fad0)

**Comment by xm4rcell0x** [comment]
Hi! that's my usb to rs485 converter, i have two of this as i try to swap because i think that was broken. 
Here my other debug with the second usb-rs485 converter:
`2023-09-18 12:35:25.820 DEBUG (MainThread) [pymodbus.logging] Connecting to None.
2023-09-18 12:35:25.820 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-09-18 12:35:25.821 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0'
2023-09-18 12:35:26.824 INFO (MainThread) [huawei_solar.huawei_solar] Waiting for connection ...
2023-09-18 12:35:31.826 ERROR (MainThread) [huawei_solar.huawei_solar] Timeout while waiting for connection. Reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-18 12:35:31.828 ERROR (MainThread) [huawei_solar.huawei_solar] Aborting client creation due to error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 210, in create_rtu
    await huawei_solar._initialize()
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 107, in _initialize
    self.time_zone = (await self.get(rn.TIME_ZONE)).value
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 241, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 276, in get_multiple
    response = await self._read_registers(registers[0].register, total_length, slave)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 396, in _read_registers
    async with self._communication_lock():
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 145, in _communication_lock
    raise err
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-18 12:35:31.831 DEBUG (MainThread) [pymodbus.logging] Connecting to None.
2023-09-18 12:35:31.831 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-09-18 12:35:31.832 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0'`

please don't close the issue, i really want to help you but the integration doesn't show me the option to download the diagnostic file because it doesn't start at all. What's the next step ?

**Comment by wlcrs** [comment]
Your logs show connectivity problems, but nothing which could be considered a bug in the integration.

Your second RS485 usb adapter is also not functioning correctly according to the logs:

```
2023-09-18 12:35:31.832 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901IVI1-if00-port0'`
```

I would advice you to verify via another way that you are still able to read modbus registers from the inverter. For that, you can plug the serial adapters in your laptop and use [qModMaster](https://sourceforge.net/projects/qmodmaster/)

After connecting to the inverter via RTU and with the proper slave id, try reading 2 registers starting at the address 32080 with function code 0x03:

![image](https://github.com/wlcrs/huawei_solar/assets/2150060/00fec51c-fcd2-4a20-884e-44dee85477df)

This should show you the current active power of your inverter, as per the Modbus Interface Definitions PDF:

![image](https://github.com/wlcrs/huawei_solar/assets/2150060/bfc8420f-be00-4ce8-aa3c-4bd728f2dd21)

Note that I fully intend to support this integration when it comes to bug fixes, but I consider connectivity problems to be user errors. With more than 1200 active installations of this integration it is not possible for me to provide free support for things that boil down to cabling problems, hardware failures (in the case of serial connections), IP address changes, properly configuring firewalls (in the case of network connections) etc. So if you want me to continue responding in this issue, you'll need to prove that the integration is at fault.

**Comment by wlcrs** [comment]
> but I think that this is some connectivity issue related to the integration.

In my last comment here I extensively outlined how you can prove to yourself/to me what your gut feelings are telling you.

I cannot do anything with gut feelings, only with properly well-substantiated bug reports and additional diagnosis to rule out problems outside of the integration.

**Comment by xm4rcell0x** [comment]
@wlcrs I apologize, but you were right. 
Both of my usb-rs485 are broken. 
I bought just now a new one and tried with qModMaster and I can read data. 
So ... excuse me 😞 and thank you for your patience with me.
