### ISSUE TITLE
[Bug]: Wong values from integration

### ISSUE THREAD

**Issue by spac3h** [wlcrs/huawei_solar#507]
### Describe the issue

Hi,

The integration is reporting values totally different from the Fusion Solar app. I am connecting to modbus via inverter AP, and i am also using the fusion solar app trough AP.

<img width="487" alt="Screenshot 2023-10-16 at 12 38 11" src="https://github.com/wlcrs/huawei_solar/assets/20891430/392d6b80-4a74-4792-bcb8-3f06f59d2d63">

![IMG_9753](https://github.com/wlcrs/huawei_solar/assets/20891430/cf16c4f0-a484-4719-b852-bdbf68d0a5ae)

Also my inverter is a SUN2000-5KTL-L1 and the integration reports that i have installed a SUN2000-2KTL-L1

Any idea on what can i misconfigured or be missing?

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-5KTL-L1
Inverter Firmware version: V200R001C00SPC130
MBUS(DC) Firmware version: V100R001C00SPC320
SDongle present: no
Power meter present: single phase
Battery: LUNA2000 5Wh / Powered Off
Battery Firmware version:

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

[config_entry-huawei_solar-94e4b0aa9768003bbc27e7d151ef7830.json.txt](https://github.com/wlcrs/huawei_solar/files/12915861/config_entry-huawei_solar-94e4b0aa9768003bbc27e7d151ef7830.json.txt)

### Upload your relevant debug logs

```text
2023-10-16 11:36:46.052 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (TimeoutError)
2023-10-16 11:36:47.055 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:36:47.056 INFO (MainThread) [backoff] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:36:48.095 ERROR (MainThread) [custom_components.huawei_solar] Timeout fetching HV21A0255655_data_update_coordinator data
2023-10-16 11:37:23.094 ERROR (MainThread) [huawei_solar.huawei_solar] Timeout while waiting for connection. Reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-10-16 11:40:08.903 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (TimeoutError)
2023-10-16 11:40:09.905 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:40:09.905 INFO (MainThread) [backoff] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:40:11.907 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:40:11.912 INFO (MainThread) [backoff] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:40:15.914 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:40:15.914 INFO (MainThread) [backoff] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:40:17.096 ERROR (MainThread) [custom_components.huawei_solar] Timeout fetching HV21A0255655_data_update_coordinator data
2023-10-16 11:41:32.418 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (TimeoutError)
2023-10-16 11:41:33.420 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:41:33.420 INFO (MainThread) [backoff] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:41:35.422 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:41:35.422 INFO (MainThread) [backoff] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:41:42.094 ERROR (MainThread) [custom_components.huawei_solar] Timeout fetching HV21A0255655_data_update_coordinator data
2023-10-16 11:42:22.099 INFO (MainThread) [backoff] Backing off _do_read(...) for 1.0s (TimeoutError)
2023-10-16 11:42:23.099 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:42:23.100 INFO (MainThread) [backoff] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:42:25.102 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:42:25.102 INFO (MainThread) [backoff] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:42:28.192 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 113] Connect call failed ('192.168.1.7', 6607)
2023-10-16 11:42:29.104 ERROR (MainThread) [huawei_solar.huawei_solar] Modbus client is not connected to the inverter.
NoneType: None
2023-10-16 11:42:29.104 INFO (MainThread) [backoff] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter.)
2023-10-16 11:43:07.098 ERROR (MainThread) [huawei_solar.huawei_solar] Timeout while waiting for connection. Reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-10-16 11:43:10.192 WARNING (MainThread) [pymodbus.logging] Failed to connect [Errno 113] Connect call failed ('192.168.1.7', 6607)
2023-10-16 11:43:42.096 ERROR (MainThread) [huawei_solar.huawei_solar] Timeout while waiting for connection. Reconnecting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(self._client.connected_event.wait(), WAIT_FOR_CONNECTION_TIMEOUT)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-10-16 11:44:25.552 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x8 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x31 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x29 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x7b 0xff 0xff 0xfe 0xbc 0x3 0x0 0x13 0x88 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x4e 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:44:25.552 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x8 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x31 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x29 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x7b 0xff 0xff 0xfe 0xbc 0x3 0x0 0x13 0x88 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x4e 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:44:25.552 DEBUG (MainThread) [pymodbus.logging] Processing: 0x10 0x8 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x31 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x29 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x7b 0xff 0xff 0xfe 0xbc 0x3 0x0 0x13 0x88 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x4e 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:44:25.552 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-10-16 11:44:25.552 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4104
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] [1, 0, 2353, 32767, 65535, 32767, 65535, 65535, 65321, 32767, 65535, 32767, 65535, 65535, 65147, 65535, 65212, 768, 5000, 3, 1874, 6, 38734, 0, 0, 0, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535]
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t1']
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff)']
2023-10-16 11:44:25.553 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe{']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe\xbc']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x03', b'\x07R']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x06', b'\x97N']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:44:25.554 INFO (MainThread) [custom_components.huawei_solar] Fetching HV21A0255655_data_update_coordinator data recovered
2023-10-16 11:46:00.093 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32064 with length 52 from slave 0
2023-10-16 11:46:00.094 DEBUG (MainThread) [pymodbus.logging] send: 0x10 0xf 0x0 0x0 0x0 0x6 0x0 0x3 0x7d 0x40 0x0 0x34
2023-10-16 11:46:00.096 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4111
2023-10-16 11:46:03.040 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0xf 0x0 0x0 0x0 0x6b 0x0 0x3 0x68 0x0 0x0 0x1 0x7d 0x9 0x32 0x0 0x0 0x0 0x0 0x4 0x81 0x0 0x2 0x0 0x0 0x0 0x0 0x6 0x6a 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x5 0x79 0x0 0x0 0x1 0x74 0x0 0x0 0x0 0x0 0x3 0xe8 0x13 0x87 0x26 0x1f 0x1 0x60 0xb 0xb8 0x2 0x0 0x0 0x0 0x65 0x2c 0xee 0x11 0x65 0x2c 0x37 0x3a 0x0 0x0 0x1 0x7b 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x7 0x36 0xac 0x0 0x7 0x78 0x26 0x65 0x2d 0x30 0x89 0x0 0x0 0x0 0x2e 0x0 0x0 0x0 0x78
2023-10-16 11:46:03.040 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0xf 0x0 0x0 0x0 0x6b 0x0 0x3 0x68 0x0 0x0 0x1 0x7d 0x9 0x32 0x0 0x0 0x0 0x0 0x4 0x81 0x0 0x2 0x0 0x0 0x0 0x0 0x6 0x6a 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x5 0x79 0x0 0x0 0x1 0x74 0x0 0x0 0x0 0x0 0x3 0xe8 0x13 0x87 0x26 0x1f 0x1 0x60 0xb 0xb8 0x2 0x0 0x0 0x0 0x65 0x2c 0xee 0x11 0x65 0x2c 0x37 0x3a 0x0 0x0 0x1 0x7b 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x7 0x36 0xac 0x0 0x7 0x78 0x26 0x65 0x2d 0x30 0x89 0x0 0x0 0x0 0x2e 0x0 0x0 0x0 0x78
2023-10-16 11:46:03.040 DEBUG (MainThread) [pymodbus.logging] Processing: 0x10 0xf 0x0 0x0 0x0 0x6b 0x0 0x3 0x68 0x0 0x0 0x1 0x7d 0x9 0x32 0x0 0x0 0x0 0x0 0x4 0x81 0x0 0x2 0x0 0x0 0x0 0x0 0x6 0x6a 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x5 0x79 0x0 0x0 0x1 0x74 0x0 0x0 0x0 0x0 0x3 0xe8 0x13 0x87 0x26 0x1f 0x1 0x60 0xb 0xb8 0x2 0x0 0x0 0x0 0x65 0x2c 0xee 0x11 0x65 0x2c 0x37 0x3a 0x0 0x0 0x1 0x7b 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x7 0x36 0xac 0x0 0x7 0x78 0x26 0x65 0x2d 0x30 0x89 0x0 0x0 0x0 0x2e 0x0 0x0 0x0 0x78
2023-10-16 11:46:03.040 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-10-16 11:46:03.040 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4111
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] [0, 381, 2354, 0, 0, 1153, 2, 0, 0, 1642, 0, 0, 0, 0, 0, 1401, 0, 372, 0, 0, 1000, 4999, 9759, 352, 3000, 512, 0, 25900, 60945, 25900, 14138, 0, 379, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 13996, 7, 30758, 25901, 12425, 0, 46, 0, 120]
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01}']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x06j']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x05y']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x01t']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'e,', b'\xee\x11']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'e,', b'7:']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x07', b'6\xac']
2023-10-16 11:46:03.041 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00x']
2023-10-16 11:46:03.093 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 32000 with length 20 from slave 0
2023-10-16 11:46:03.093 DEBUG (MainThread) [pymodbus.logging] send: 0x10 0x10 0x0 0x0 0x0 0x6 0x0 0x3 0x7d 0x0 0x0 0x14
2023-10-16 11:46:03.093 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4112
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x10 0x0 0x0 0x0 0x2b 0x0 0x3 0x28 0x0 0x6 0x0 0x0 0x0 0x7 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x38 0x11 0x6 0x6d 0x0 0xf2 0x0 0x0 0x0 0x0
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x10 0x0 0x0 0x0 0x2b 0x0 0x3 0x28 0x0 0x6 0x0 0x0 0x0 0x7 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x38 0x11 0x6 0x6d 0x0 0xf2 0x0 0x0 0x0 0x0
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] Processing: 0x10 0x10 0x0 0x0 0x0 0x2b 0x0 0x3 0x28 0x0 0x6 0x0 0x0 0x0 0x7 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x38 0x11 0x6 0x6d 0x0 0xf2 0x0 0x0 0x0 0x0
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4112
2023-10-16 11:46:03.344 DEBUG (MainThread) [pymodbus.logging] [6, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14353, 1645, 242, 0, 0]
2023-10-16 11:46:03.345 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:46:03.396 DEBUG (MainThread) [huawei_solar.huawei_solar] Reading register 37100 with length 38 from slave 0
2023-10-16 11:46:03.396 DEBUG (MainThread) [pymodbus.logging] send: 0x10 0x11 0x0 0x0 0x0 0x6 0x0 0x3 0x90 0xec 0x0 0x26
2023-10-16 11:46:03.397 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4113
2023-10-16 11:46:03.499 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x11 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x2f 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x17 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x43 0xff 0xff 0xfe 0xbd 0x3 0x26 0x13 0x87 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x50 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:46:03.499 DEBUG (MainThread) [pymodbus.logging] recv: 0x10 0x11 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x2f 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x17 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x43 0xff 0xff 0xfe 0xbd 0x3 0x26 0x13 0x87 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x50 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:46:03.499 DEBUG (MainThread) [pymodbus.logging] Processing: 0x10 0x11 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x0 0x1 0x0 0x0 0x9 0x2f 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xff 0x17 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0xff 0xff 0xfe 0x43 0xff 0xff 0xfe 0xbd 0x3 0x26 0x13 0x87 0x0 0x3 0x7 0x52 0x0 0x6 0x97 0x50 0x0 0x0 0x0 0x0 0x0 0x0 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff 0x7f 0xff 0xff 0xff
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4113
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] [1, 0, 2351, 32767, 65535, 32767, 65535, 65535, 65303, 32767, 65535, 32767, 65535, 65535, 65091, 65535, 65213, 806, 4999, 3, 1874, 6, 38736, 0, 0, 0, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535, 32767, 65535]
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\t/']
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xff\x17']
2023-10-16 11:46:03.500 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfeC']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\xff\xff', b'\xfe\xbd']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x03', b'\x07R']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x06', b'\x97P']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x00\x00', b'\x00\x00']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [pymodbus.logging] handle: [b'\x7f\xff', b'\xff\xff']
2023-10-16 11:46:03.501 DEBUG (MainThread) [custom_components.huawei_solar] Finished fetching HV21A0255655_data_update_coordinator data in 3.409 seconds (success: True)
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
I've never seen an inverter misreporting its model number before. Please verify that you are not mixing up two unrelated inverters. The SN of the inverter of which you've included the logs is HV21A0255655 . Please verify that SN in your FusionSolar app and on the sticker on your inverter.

**Comment by spac3h** [comment]
Hi, the error was on me, a neighbor has an inverter which i can connect to with same credentials and i was connecting to his inverter 🤦 . Thanks for your help.
