### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by macrojames** [wlcrs/huawei_solar#510]
### Describe the issue

After enabling another entity, HA tries to reload the integration and fails on unloading the services.

I think it is just a `)` too far to the right.

### Bescribe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version:
SDongle present: yes 
Power meter present: three phase
Battery: LUNA2000 5kWh 
Battery Firmware version:

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Impossible after the bug hit

### Upload your relevant debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_solar/__init__.py", line 218, in async_unload_entry
    await async_cleanup_services(hass)
  File "/config/custom_components/huawei_solar/services.py", line 680, in async_cleanup_services
    if len(hass.data[DOMAIN] == 1):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()
```

### Please confirm the following:

- [X] The problem is still present in the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [X] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by macrojames** [comment]
Seems already fixed in #482, I didn't search the correct terms.
