### ISSUE TITLE
[Bug]: Delete

### ISSUE THREAD

**Issue by giuseppe072000** [wlcrs/huawei_solar#517]
### Describe the issue

After HA   Update not was  possible to use Huawei Solar massage is "Not Loaded"

It was reinstalled HACS  and no difference.
 

Before HA update connection with  inverter and mart meter was ok

Download diagnosis in not avilable 

2023-10-28 22:38:32.197 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

### Bescribe your Huawei Solar Setup

Inverter Type:
Inverter Firmware version:
SDongle present: yes / no
Power meter present: three phase / single phase / no
Battery: LG RESU xxkWh / LUNA2000 xxkWh / None
Battery Firmware version:

### How do you connect to the inverter?

Via the SDongle, wired connection

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.
[home-assistant_2023-10-28T19-39-50.303Z.log](https://github.com/wlcrs/huawei_solar/files/13196588/home-assistant_2023-10-28T19-39-50.303Z.log)

### Upload your relevant debug logs

```text
2023-10-28 22:38:32.197 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

### Please confirm the following:

- [x] The problem is still present in the latest release of this integration.
- [x] I did not find an existing issue describing this problem.
- [x] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [x] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by wlcrs** [comment]
The actual error is:

```
2023-10-28 22:39:16.556 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.huawei_solar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/huawei_solar/__init__.py", line 25, in <module>
    from huawei_solar import HuaweiSolarBridge, HuaweiSolarException, InvalidCredentials
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/__init__.py", line 6, in <module>
    from .bridge import HuaweiSolarBridge  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/bridge.py", line 22, in <module>
    from huawei_solar.huawei_solar import AsyncHuaweiSolar, Result
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 14, in <module>
    from pymodbus.client.asynchronous.async_io import (
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 228, in <module>
    class ReconnectingAsyncioModbusTcpClient(object):
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 262, in ReconnectingAsyncioModbusTcpClient
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

Your HA instance seems to have a broken Python version. I cannot help you with that.
