### ISSUE TITLE
[Bug]: Intergration not loading with 2024.3

### ISSUE THREAD

**Issue by yousaf465** [wlcrs/huawei_solar#636]
### Describe the issue

Huawei_solar integration is not loading with 2024.3b0. 
![image](https://github.com/wlcrs/huawei_solar/assets/83491212/905f2266-a151-4c81-9639-7b9f60f5a032)

### Bescribe your Huawei Solar Setup

10KTLM1 

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

I can't download it as the integration is not loaded. 

### Upload your relevant debug logs

```text
Logger: homeassistant.bootstrap
Source: util/json.py:84
First occurred: 11:33:53 (1 occurrences)
Last logged: 11:33:53

Error setting up integration huawei_solar - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 78, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 595 column 131 (char 19468)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 179, in async_setup_component
    await future
  File "/usr/src/homeassistant/homeassistant/setup.py", line 179, in async_setup_component
    await future
  File "/usr/src/homeassistant/homeassistant/setup.py", line 158, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/setup.py", line 427, in _async_setup_component
    await load_translations_task
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 509, in async_load_integrations
    await _async_get_translations_cache(hass).async_load(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 239, in async_load
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 292, in _async_load
    translation_by_language_strings = await _async_get_component_strings(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 188, in _async_get_component_strings
    loaded_translations_by_language = await hass.async_add_executor_job(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 84, in _load_translations_files_by_language
    loaded_json = load_json(translation_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 84, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: unexpected character: line 595 column 131 (char 19468)
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [ ] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by yousaf465** [comment]
https://discord.com/channels/330944238910963714/427516175237382144/1212449004541972567 I think this might be relevant.

**Comment by yousaf465** [comment]
```Logger: homeassistant.util.json
Source: util/json.py:78
First occurred: 11:30:05 (2 occurrences)
Last logged: 11:31:51

Could not parse JSON content: /config/custom_components/huawei_solar/translations/ur.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 78, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 595 column 131 (char 19468)

```
another error

**Comment by adepedroblanes** [comment]
Me ocurre lo mismo, pero creo que es la wifi modbus del inversor que se desconecta.

The same thing happens to me, but I think it is the inverter's modbus wifi that disconnects.

**Comment by yousaf465** [comment]
fixed for Urdu at least.
