### ISSUE TITLE
[Bug]: Unexpected Error during setup with elevate permissions enabled

### ISSUE THREAD

**Issue by mada199122** [wlcrs/huawei_solar#855]
### Describe the issue

Until yesterday everything was working fine with the elevate permissions enabled.
this morning I've updated Home Assistant to the latest version and after the restart, the integration failed to load.
I've tried to reload the extension but it didn't work.
I've tried to delete the extension, reboot HA and add agin the extension but now I always get the Unexpected Error message when the extension try to login with the credentials.
![Screenshot 2024-11-24 at 13 34 16](https://github.com/user-attachments/assets/5dc2be91-9118-48e1-89bb-f8bc257d07cb)
If I configure the extension without elevate permissions the setup complete correctly and the extension is able to retrieve the information correctly from the inverter.

I've tried the latest alpha version but the same behaviour happens with the 1.4.1 too.
I've tried to revert back Home Assistant to the 2024.11.2 without success.

Can you please help me?
Thanks in advance

### Describe your Huawei Solar Setup

Inverter Type: SUN2000L-4KTL-L1
Inverter Firmware version: V200R001C00SPC130
sDongle present: Yes
sDongle Type: sDongleA-05 (WiFi ) 
sDongle Connectivity: WiFi 
sDongle Firmware: 
Power meter present: single phase
Optimizers Present: / No
Battery:  None
Huawei Solar integration version: 1.5.0a but the issue is present even with the 1.4.1

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
2024-11-24 13:35:28.766 ERROR (MainThread) [custom_components.huawei_solar.config_flow] Unexpected exception while validating login parameters via ModbusTCP
Traceback (most recent call last):
  File "/config/custom_components/huawei_solar/config_flow.py", line 612, in async_step_network_login
    login_success = await validate_network_setup_login(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_solar/config_flow.py", line 268, in validate_network_setup_login
    await bridge.login(username, password)
  File "/usr/local/lib/python3.12/site-packages/huawei_solar/bridge.py", line 327, in login
    if not await self.client.login(username, password, self.slave_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/huawei_solar/huawei_solar.py", line 824, in login
    return await _do_login()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/huawei_solar/huawei_solar.py", line 805, in _do_login
    await self._client.execute(login_request),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 183, in async_execute
    raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by mada199122** [comment]
I discovered the issue. I don't know why but the inverter has lost the configuration of the installer password.
Setting it with the Fusion solar up fixed this problem.
Now I can login again
