### ISSUE TITLE
[Bug]: Help for Actions needed

### ISSUE THREAD

**Issue by viper539** [wlcrs/huawei_solar#868]
### Describe the issue

Hi, i really like what you have build here.
I'm currently struggling with the Action: Huawei Solar: Set Fixed Charge Periods
I created a period via template, but it wouldn't accept it.

This, via Dev-tools->Actions, works:
`action: huawei_solar.set_fixed_charge_periods
data:
  device_id: <long key>
  periods: |
    {{states('sensor.batterie_laden_value')}}
`

This, via button, not:
`type: button
tap_action:
  action: none
hold_action:
  action: perform-action
  confirmation:
    text: Batterie Ladeperiode speichern?
  perform_action: huawei_solar.set_fixed_charge_periods
  target: {}
  data:
    device_id: <long key>
    periods: |
      {{states('sensor.batterie_laden_value')}}
show_state: false
icon: mdi:battery-charging
name: setze Ladeperiode`

sensor.batterie_laden_value = "05:30-06:00/6000W"

HD tells me:
"Failed to perform the action huawei_solar/set_fixed_charge_periods. Invalid periods"

I would be very happy when you could add some examples to the Documentation.

Thank you very much!
viper539

### Describe your Huawei Solar Setup

Inverter Type: SUN2000-10KTL-M1
Inverter Firmware version: V100R001C00SPC161
sDongle present: Yes
sDongle Type: sDongleA-05 (WiFi / Ethernet)
sDongle Connectivitiy: WiFi
sDongle Firmware: V100R001C00SPC133
Power meter present: three phase
Optimizers Present: No
Battery: LUNA2000 10KW-C1
Battery Firmware version: unknown
Huawei Solar integration version: unknown

### How do you connect to the inverter?

Via the `SUN2000-<serial_no>` WiFi

### Upload your Diagnostics File

Drag & Drop your Diagnostics File here.

### Upload your relevant debug logs

```text
2024-12-11 02:24:43.756 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139875847375744] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_solar/services.py", line 604, in set_fixed_charge_periods
    raise ValueError("Invalid periods")
ValueError: Invalid periods
```

### Please confirm the following:

- [X] I'm running the latest release of Home Assistant.
- [X] I'm running the latest release of this integration.
- [X] I did not find an existing issue describing this problem.
- [ ] I did upload the diagnostics-file that I could retrieve from  the 'Devices & Services Page'
- [X] I did upload the relevant debug logs (via 'Enable Debug Logging'-feature or by manually configuring HA logging)

**Comment by scruysberghs** [comment]
looks like a similar error is trown when I try to call :
```
action: huawei_solar.set_capacity_control_periods
data:
  device_id: f0c20b3b4e7a1af202ae2bca230becbe
  periods: 00:00-23:59/1234567/5200W
```
`Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 5:30:29 PM (2 occurrences)
Last logged: 5:54:55 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'tuple' object has no attribute 'set'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_solar/services.py", line 575, in set_capacity_control_periods
    await bridge.set(
          ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'set'

-----
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/huawei_solar/services.py:573
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 5:30:40 PM (3 occurrences)
Last logged: 5:31:20 PM
[139632520784064] Error handling message: Unknown error (unknown_error) Steven Cruysberghs from 100.93.213.49 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 816, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_solar/services.py", line 573, in set_capacity_control_periods
    raise ValueError("Invalid periods")
ValueError: Invalid periods`

**Comment by wlcrs** [comment]
I've made the error message somewhat more verbose to help me understand the problem.

In both of your cases, you provide a valid example of a period. I manually tested them against the 2 regular expressions which do that validation:

![Image](https://github.com/user-attachments/assets/0cb3ebf8-132f-4344-90a9-7debe743e21c)

![Image](https://github.com/user-attachments/assets/2df08797-ad7b-4905-8947-20180af72b85)

green == recognized as valid input.

Please test again with the next release once it is released (next = the one after 1.5.0 beta 2)

**Comment by scruysberghs** [comment]
1.5.0b2 fixed things for me with the period related action calls from home assistant

This now works for me:
```
action: huawei_solar.set_capacity_control_periods
data:
  device_id: 26bcd7155fde1ddaf0ad1b610aebcaa9
  periods: 00:00-23:59/1234567/4100W
```

![Image](https://github.com/user-attachments/assets/8a827f12-24fa-402f-a40e-3d29b695c141)
